<p align="center">
title: Gerson A Morales
</p>
logo: /assets/img/Head Shot.png
description:
- | 
  MAnalytx student @ UC Berkeley 
  Connect with me on <a href="https://www.linkedin.com/in/gersonmoralesd/">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
